name: Bastian Greshake
bio: 'A frustrated grad student who enjoys liberating data'
picture: 'assets/images/profile.jpg'

url: http://gedankenstuecke.github.io
#url: localhost:3000
# your url: http://USERNAME.github.io
permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics: 'UA-MYANALYTICS'
#disqus: mydisqus
facebook: bastian.greshake
twitter: gedankenstuecke
instagram: gedankenstuecke
#linkedin: mylinkedin
#youtube: myyoutube
#spotify: myspotify
github: gedankenstuecke
scholar: xmtDOnQAAAAJ
orcid: 0000-0002-9925-9623
email: bgreshake@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
#paginate: 10
#paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need about or blog, comment them out below
about: true
blog: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
